apiVersion: apps/v1
kind: Deployment
metadata:
  name: enowshop-api-metrics-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enowshop-api-metrics
  template:
    metadata:
      labels:
        app: enowshop-api-metrics
    spec:
      containers:
        - name: enowshop-api-metrics
          image: gcr.io/enowhop/enowshop-api-metrics:1
          ports:
              - containerPort: 8081